name: 🐞 Bug Report
description: Report a bug on Gravity Assist
labels: ["bug"]
title: "bug: "
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe what should have happened when you encountered the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please provide any reproduction steps that may need to be described. E.g. if the bug happens every other day except Tuesdays, make sure that's mentioned.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Please provide any additional information related to the bug. Screenshots, code snippets, and logs are useful.
