name: 🔥 New Feature
description: Add a new feature to Gravity Assist
labels: ["enhancement"]
title: "feature: "
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what you want to do.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Rationale
      description: Why should this be added?
    validations:
      required: true
